HW06 Borovlev
kajigor/fp-2024-cub-fall pull request #132
Opened 2024-11-07 21:12 UTC by petyb

2024-11-12 10:42 UTC, kajigor requested changes

2024-11-12 10:42 UTC, kajigor commented on monads/src/FailCont/Main.hs
> +      Just y -> f (Right (x + y))
Create a helper function that does `readMaybe` and returns `Either`. This way, your code will be way more beautiful.

2024-11-12 14:42 UTC, petyb commented on monads/src/FailCont/Main.hs
> +      Just y -> f (Right (x + y))
Makes sense, now it is much better

2024-11-15 18:31 UTC, kajigor commented
ok

2024-11-15 18:31 UTC, closed without merging