Kenesbek HW07
kajigor/fp-2024-cub-fall pull request #140
Opened 2024-11-14 15:37 UTC by serzhan-kenesbek

2024-11-14 15:40 UTC, serzhan-kenesbek commented
Most important files:
PBT/test/Test/Compiler.hs
PBT/test/Test/Interpreter.hs
PBT/test/Test.hs
7_2.txt

2024-11-14 23:23 UTC, serzhan-kenesbek commented
Timestamps for my participation and dates:
04/10/2024 - Proof: Two screenshots of the Transcript
<img width="1512" alt="Screenshot 2024-11-15 at 00 13 49" src="https://github.com/user-attachments/assets/b313b67f-6274-4f56-84d0-042a735ed601">
<img width="1512" alt="Screenshot 2024-11-15 at 00 13 54" src="https://github.com/user-attachments/assets/d122ac5d-265e-40de-bd74-167fd006653b">

18/10/2024 - Proof: Two screenshots of timestamps
<img width="1512" alt="Screenshot 2024-11-15 at 00 10 00" src="https://github.com/user-attachments/assets/d606327d-99a5-4a54-b92c-69508273f2ef">
<img width="1512" alt="Screenshot 2024-11-15 at 00 11 39" src="https://github.com/user-attachments/assets/c575f9cb-e555-4692-b3ac-020d78c7a4b7">

06/11/2024 - Proof: Screenshot of a timestamp
<img width="1512" alt="Screenshot 2024-11-14 at 23 59 55" src="https://github.com/user-attachments/assets/4663404a-6222-4d7a-b722-818d9f5e14da">

2024-11-15 17:24 UTC, kajigor commented
2 ok

2024-11-15 17:41 UTC, kajigor requested changes

2024-11-15 17:41 UTC, kajigor commented on PBT/test/Test/Compiler.hs
> +  return $ E.Plus left right
These are rather weak generators. Use `Gen.recursive` to generate random expressions and test them.

2024-11-15 17:41 UTC, kajigor commented on PBT/test/Test/Compiler.hs
> +evalExpr :: E.Expr v -> Int
You can implement the whole interpreter.

2024-11-15 17:41 UTC, kajigor commented on PBT/test/Test/Compiler.hs
> +      failure
Generalize these properties and check that compiled expression evaluates to the same result.

2024-12-01 12:22 UTC, kajigor commented
Ok

2024-12-01 12:22 UTC, closed without merging