Paniukhin HW07
kajigor/fp-2024-cub-fall pull request #149
Opened 2024-11-15 03:01 UTC by npanuhin

2024-11-15 18:15 UTC, kajigor commented
2: no solution

2024-11-15 18:18 UTC, kajigor requested changes

2024-11-15 18:18 UTC, kajigor commented on monads/test/Spec.hs
> +  return (val1 + val2)
What about `Let`?

2024-11-15 18:19 UTC, kajigor commented
You have a bunch of really good properties, but could you add let-expressions to the generator and the interpreter?

2024-11-16 21:02 UTC, npanuhin commented on monads/test/Spec.hs
> +  return (val1 + val2)
[Added](https://github.com/kajigor/fp-2024-cub-fall/pull/149/commits/049306b7efbbd2309d30a76fcdee133cbf2f2a45#diff-0e851a1a04a54af327b8044f27cdd1c408a2fee485bb48c4638e5656bdb5e8a3R109-R111)

2024-11-16 21:03 UTC, npanuhin commented
Added Let-expressions to `evalDirect` and `prop_directEvaluationConsistency` test

2024-12-01 12:27 UTC, kajigor commented
Ok.

2024-12-01 12:27 UTC, closed without merging