Kenesbek Proj
kajigor/fp-2024-cub-fall pull request #152
Opened 2024-11-22 21:49 UTC by serzhan-kenesbek

The game is playable in the Terminal. 

There are currently no Tests yet, as I wanted to first get feedback on the implementation before creating them. 

In Explanations.txt file I documented my thinking process when creating most features. Will later turn it into a proper documentation.

2024-11-27 11:21 UTC, kajigor commented
There's something going wrong: it sometimes hangs, for example: 

![Screenshot 2024-11-27 at 12 20 38](https://github.com/user-attachments/assets/d44712ba-1f6c-4734-8f4c-ea92c4d3b720)

2024-11-27 11:38 UTC, kajigor requested changes

2024-11-27 11:38 UTC, kajigor commented on minesweeper/src/Grid/Generation.hs
> +  length [ () | neighbor <- getNeighbors index rows cols, isMine (flatGrid !! neighbor) ]
https://hackage.haskell.org/package/ghc-9.10.1/docs/GHC-Utils-Misc.html#v:count

2024-11-27 11:38 UTC, kajigor commented on minesweeper/src/Grid/Core.hs
> +    mapM_ renderRow (zip ([0 ..] :: [Int]) grid) -- Had a warning because mapM_ can't infer the type of the list being passed to it. That's why the list passed to zip is explicitly Int
You could also specify the type of `renderRow`.

2024-11-27 11:38 UTC, kajigor commented on minesweeper/src/Grid/Core.hs
> +        | isRevealed cell                 = show (adjacentMines cell) ++ "   "
It doesn't matter in a grand scheme of things, but I'd reorder the `isMine` and `isRevealed` check to avoid doing the latter twice.

2024-11-27 11:38 UTC, kajigor commented on Explanations.txt
> +Instead used Sets since they already handle the duplicates.
I bet there's a way to repeat monadic action infinitely many time in a lazy fashion and then take enough elements from the prefix to have n unique numbers.

2024-11-27 11:38 UTC, kajigor commented on minesweeper/src/Game.hs
> +        _ -> Nothing
I'd also skipped whitespace between inputs.

2024-11-27 11:38 UTC, kajigor commented on minesweeper/src/Game.hs
> +    | mines >= rows * cols = Left "Number of mines must be less than the total number of cells."
There's nothing wrong with placing a mine in every cell 🥲

2024-11-27 11:38 UTC, kajigor commented on Explanations.txt
> +One of them was that I forgot to take into account that the first move that the player makes should never turn out to be a mine.
Well... The version of a minesweeper game I had in my childhood allowed the user to blow up at the first move.

2024-11-27 11:38 UTC, kajigor commented on minesweeper/src/Game.hs
> +                        else checkGameState updatedGrid row col rows cols
Excessive checks

2024-11-27 11:38 UTC, kajigor commented on minesweeper/src/Game.hs
> +    case parseInput input of
I'd introduce a function

2024-11-27 11:38 UTC, kajigor commented on minesweeper/src/Grid/Core.hs
> +type Grid = [[Cell]]
Using lists may be a tad slow. Can you explore which dimensions cause a noticeable lag?

2024-12-02 16:03 UTC, serzhan-kenesbek commented
Made changes as requested, fixed and understood the first bug, added testing (both Unit and Property-Based), and added final documentation in report.pdf

2024-12-08 17:36 UTC, kajigor commented
Blows up: 

```
Ekaterina.Verbitskaya@NVC00653 minesweeper % stack run
Enter grid dimensions and number of mines (e.g., rows,cols,mines):
3,1,2
      0
  --------
  0 | .   |
  --------
  1 | .   |
  --------
  2 | .   |
  --------

Enter your first move (row,column):
1,0
minesweeper: Too many mines: Cannot place 2 mines in a grid with only 0 valid cells.
CallStack (from HasCallStack):
  error, called at src/Grid/Generation.hs:64:31 in minesweeper-0.1.0.0-2hDQarTrxVG3Aaa6xdcYbH:Grid.Generation
```

2024-12-08 17:41 UTC, serzhan-kenesbek commented
It is intended behavior. If there are too many mines it throws an error

2024-12-08 18:01 UTC, kajigor commented
Throwing exceptions into a user must never be done. If you, for some reason, think that 2 mines don't fit into 3 cells, warn the user, and do it when creating the grid, not after the first move.

2024-12-08 18:04 UTC, serzhan-kenesbek commented
Yeah makes sense. My bad. It's just that having a 3x1 grid with two mines would mean that you win with your first move. This way I was also trying to prevent the bug that you noticed when I submitted previously

2024-12-08 20:47 UTC, serzhan-kenesbek commented
Fixed it

2024-12-08 21:32 UTC, kajigor commented
Ok. Good job 👍

2024-12-08 21:32 UTC, closed without merging