Imran Turganov project
kajigor/fp-2024-cub-fall pull request #162
Opened 2024-12-05 22:49 UTC by 1MRUN

2024-12-09 17:00 UTC, kajigor commented
It would have been better to report the error as soon as it happened. 

```
% cabal run
Enter the size of the Board:
8 200 200
Enter the screen Width:
200 
Enter the screen Height:
200
Error: Invalid input detected.
```

2024-12-09 17:10 UTC, kajigor commented
Also, the ability to close the window, and basic validation that the field is even going to fit the window would be nice.

2024-12-09 17:16 UTC, kajigor requested changes

2024-12-09 17:16 UTC, kajigor commented on ReversiFinal/src/Logic.hs
> +        directions = [(dx, dy) | dx <- [-1..1], dy <- [-1..1], (dx, dy) /= (0, 0)]
code duplication

2024-12-09 17:16 UTC, kajigor commented on ReversiFinal/src/Logic.hs
> +isDirectionValid game (x, y) (dx, dy) = (any (== Just (player game)) $ takeWhile (\f -> f /= Nothing) $ tail $ map (\k -> safeAccess board (n game) (x + k * dx, y + k * dy)) [1..(n game)]) && (safeAc
unreadable

2024-12-09 17:16 UTC, kajigor commented on ReversiFinal/src/Logic.hs
> +flipCells game (x, y)
It's not good style to place definitions this far from their type signatures

2024-12-09 17:16 UTC, kajigor commented on ReversiFinal/src/Logic.hs
> +            | length (filter (== Just Player1) $ elems $ gameBoard game) < length (filter (== Just Player2) $ elems $ gameBoard game) = Just Player2
Code duplication

2024-12-09 17:16 UTC, kajigor commented on ReversiFinal/test/Main.hs
> +
Not a very interesting property

2024-12-09 17:17 UTC, kajigor commented
You have an exorbitant amount of code duplication, which should be fixed.

2025-01-02 13:52 UTC, 1MRUN commented on ReversiFinal/src/Logic.hs
> +        directions = [(dx, dy) | dx <- [-1..1], dy <- [-1..1], (dx, dy) /= (0, 0)]
changed

2025-01-02 13:52 UTC, 1MRUN commented on ReversiFinal/src/Logic.hs
> +isDirectionValid game (x, y) (dx, dy) = (any (== Just (player game)) $ takeWhile (\f -> f /= Nothing) $ tail $ map (\k -> safeAccess board (n game) (x + k * dx, y + k * dy)) [1..(n game)]) && (safeAc
Should be more readable now

2025-01-02 13:53 UTC, 1MRUN commented on ReversiFinal/src/Logic.hs
> +flipCells game (x, y)
added definition next to it.

2025-01-02 13:53 UTC, 1MRUN commented on ReversiFinal/src/Logic.hs
> +            | length (filter (== Just Player1) $ elems $ gameBoard game) < length (filter (== Just Player2) $ elems $ gameBoard game) = Just Player2
fixed it.

2025-01-03 22:14 UTC, 1MRUN commented
> Also, the ability to close the window, and basic validation that the field is even going to fit the window would be nice.

The Gloss module already provides the ability to close the game by pressing escape button.

2025-01-06 10:11 UTC, kajigor commented
The interface is severely lacking. No proper error messages; closing the window is impossible. 

```
Enter the size of the Board:
4 4
Enter the screen Width:
100 
Enter the screen Height:
100
Error: Invalid input detected.
```

80/100

2025-01-06 10:11 UTC, closed without merging