Proj Lezhnev (Haskudoku)
kajigor/fp-2024-cub-fall pull request #163
Opened 2024-12-05 22:52 UTC by Splatjov

2024-12-11 09:01 UTC, kajigor requested changes

2024-12-11 09:01 UTC, kajigor commented on app/Main.hs
> +                            Left _ -> text "Valid but Unsolvable"
When is this even possible?

2024-12-11 09:01 UTC, kajigor commented on src/Sudoku.hs
> +        "expert" -> randomRIO (61, 68)
An ordinary puzzle with a unique solution must have at least 17 clues.

2024-12-11 09:02 UTC, kajigor commented
It's helpful when you have boxes with borders. Can you also make given numbers look distinctly?

2024-12-30 15:45 UTC, Splatjov commented on app/Main.hs
> +                            Left _ -> text "Valid but Unsolvable"
It depends on definition of "Valid". There can be unsolvable layout even if it does not violate sudoku rules. 
<img width="774" alt="Screenshot 2024-12-30 at 16 15 56" src="https://github.com/user-attachments/assets/d97870a6-39fc-44bd-a08a-455e0cfc480c" />
<img width="482" alt="Screenshot 2024-12-30 at 16 13 01" src="https://github.com/user-attachments/assets/96c3be2a-de0a-4853-9707-ccbcc8e96aa6" />

2025-01-06 10:03 UTC, kajigor commented on app/Main.hs
> +                            Left _ -> text "Valid but Unsolvable"
afaik, this can only happen if your initial grid allows for several possible solutions, which should be refuted at the generation stage.

2025-01-06 10:03 UTC, kajigor commented
ok

2025-01-06 10:03 UTC, closed without merging