Kenesbek Serzhan HW01
kajigor/fp-2024-cub-fall pull request #19
Opened 2024-09-19 21:28 UTC by serzhan-kenesbek

2024-09-20 08:32 UTC, kajigor requested changes

2024-09-20 08:32 UTC, kajigor commented on Main.hs
> +short xs = length (take 3 xs) < 3
There is a way easier what to check that a list is short.

2024-09-20 08:32 UTC, kajigor commented on Main.hs
> +    "Neptune" -> ageInSeconds / (164.79132 * earthYearInSeconds)
Avoid code duplication by introducing a function to do this computation.

2024-09-26 23:07 UTC, alex28sh commented
ok

2024-09-26 23:07 UTC, closed without merging