Serize
kajigor/fp-2024-cub-fall pull request #20
Opened 2024-09-19 21:34 UTC by joseserize0222

2024-09-20 08:35 UTC, kajigor requested changes

2024-09-20 08:35 UTC, kajigor commented on Main.hs
There is a way to implement this function in 2 lines. Can you do it? 

Also, avoid introducing variables names you aren't using. Instead, use wildcards.

2024-09-20 08:35 UTC, kajigor commented on Main.hs
> +lovely xs = short xs
What about `[1,2,14]`?

2024-09-20 08:35 UTC, kajigor commented on Main.hs
> +  _ -> False
What about negative years?

2024-09-26 23:08 UTC, alex28sh commented on Main.hs
> +short xs = length (take 3 xs) <= 2
There is an overhead in your solution

2024-09-26 23:10 UTC, alex28sh commented on Main.hs
> +                            _ -> False
it seems, like your solution has too much nesting

I would advice to avoid writing such code

2024-09-26 23:11 UTC, alex28sh commented
ok

2024-09-26 23:11 UTC, closed without merging