Filipenkov
kajigor/fp-2024-cub-fall pull request #21
Opened 2024-09-19 22:01 UTC by vanutp

2024-09-20 08:38 UTC, kajigor requested changes

2024-09-20 08:38 UTC, kajigor commented on Main.hs
> +short _ = False
There is a way to implement this in 2 lines. Can you do it?

2024-09-20 08:38 UTC, kajigor commented on Main.hs
> +rightTriangles = []
?

2024-09-20 08:38 UTC, kajigor commented on Main.hs
> +isLeapYear year = (year `mod` 4 == 0) && (year `mod` 100 /= 0 || year `mod` 400 == 0)
What about negative years?

2024-09-26 23:12 UTC, alex28sh commented
ok

2024-09-26 23:12 UTC, closed without merging