Borovlev Petr HW02
kajigor/fp-2024-cub-fall pull request #23
Opened 2024-09-23 10:49 UTC by petyb

2024-09-25 17:57 UTC, alex28sh commented on Main.hs
> +productOfDifference [_] = error "list is too short"
repeating code

2024-09-25 18:00 UTC, alex28sh commented on Main.hs
> +productOfDifference ls = foldl (*) 1 (zipWith (-) (init ls) (tail ls))
you could have done without `init ls` since zipWith produces list with the length equal to the minimum length of both lists

2024-09-25 18:01 UTC, alex28sh commented on Main.hs
> +isSorted [_] = True
There is more elegant way (without code repetitions) by using zipWith

2024-09-25 18:03 UTC, alex28sh commented on Main.hs
> +interleave a b = foldl (\ls (a, b) -> ls ++ [a, b]) [] (zip a b)
There is more elegant way without list concatenation every time

2024-09-25 18:28 UTC, alex28sh requested changes
5/8

2024-09-30 12:37 UTC, kajigor commented
Good.

2024-09-30 12:37 UTC, closed without merging