Escarrá HW02
kajigor/fp-2024-cub-fall pull request #27
Opened 2024-09-24 12:47 UTC by Alain-David-001

2024-09-25 18:30 UTC, alex28sh requested changes
4/8

2024-09-25 18:30 UTC, alex28sh commented on Main.hs
> +productOfDifference (x : xs) = productOfDifference xs * (x - head xs)
What about using `zipWith`?

2024-09-25 18:30 UTC, alex28sh commented on Main.hs
> +isSorted (x:xs) = x <= head xs && isSorted xs
What about higher-order functions?

2024-09-25 18:30 UTC, alex28sh commented on Main.hs
> +dotProduct (a:as) (b:bs) = a*b + dotProduct as bs
again

2024-09-25 18:30 UTC, alex28sh commented on Main.hs
> +interleave as bs = concat (zipWith (\ a b -> [a,b]) as bs)
you don't need first 2 pattern-matchings

2024-09-30 12:51 UTC, kajigor commented on Main.hs
> +productOfDifference [a] = error "List cannot be empty"
It's better not to name variables that you aren't gonna use.

2024-09-30 12:52 UTC, kajigor commented on Main.hs
> +powerByIndex a = zipWith (^) a [0 ..]
You could have avoided introducing the named variable by using `flip`

2024-09-30 12:52 UTC, kajigor commented
Good.

2024-09-30 12:52 UTC, closed without merging