Matheas-Roland Borsos HW2
kajigor/fp-2024-cub-fall pull request #30
Opened 2024-09-24 20:07 UTC by matyborsos

2024-09-25 18:35 UTC, alex28sh requested changes

2024-09-25 18:35 UTC, alex28sh commented on Main.hs
> +    | otherwise = product $ zipWith (-) xs (drop 1 xs)
Simple advise: use `tail` instead of `drop 1`

2024-09-25 18:35 UTC, alex28sh commented on Main.hs
> +interleave (x : xs) (y : ys) = x : y : interleave xs ys
A lot of code, what about using higher-order functions on lists?

2024-09-30 12:54 UTC, kajigor commented
Good.

2024-09-30 12:54 UTC, closed without merging