Razkalla/HW02
kajigor/fp-2024-cub-fall pull request #33
Opened 2024-09-25 13:52 UTC by AbanoubSeddik

2024-09-25 18:39 UTC, alex28sh requested changes
4/8

2024-09-25 18:39 UTC, alex28sh commented on Main.hs
> +isSorted (x:y:xs) = x <= y && isSorted (y:xs)
What about using higher-order functions?

2024-09-25 18:39 UTC, alex28sh commented on Main.hs
> +  (if z == x then 1 else 0) + countElement z xs
again

2024-09-25 18:39 UTC, alex28sh commented on Main.hs
> +dotProduct xs ys = sum [x * y | (x, y) <- zip xs ys]
zipWith?

2024-09-25 18:39 UTC, alex28sh commented on Main.hs
> +interleave (x:xs) (y:ys) = x:y: interleave xs ys
Too much code, use higher-order functions on lists

2024-09-30 13:02 UTC, kajigor commented
Good.

2024-09-30 13:02 UTC, closed without merging