Enrike Valentinov Homework 2
kajigor/fp-2024-cub-fall pull request #40
Opened 2024-09-26 21:41 UTC by Enrike04

2024-09-26 23:28 UTC, alex28sh commented on Main.hs
> +prodList (h:t) = h * prodList t
you should use functions discussed in lecture instead this

2024-09-26 23:28 UTC, alex28sh commented on Main.hs
> +short _ = False
this check can be done in 2 lines (also you don't need it in separate function)

2024-09-26 23:29 UTC, alex28sh commented on Main.hs
> +    where compareNextNumber = countElement x ys
you should use fhigher order unctions discussed in lecture

2024-09-26 23:30 UTC, alex28sh commented on Main.hs
> +sumList (h:t) = h + sumList t
you should use fhigher order unctions discussed in lecture instead this

2024-09-26 23:31 UTC, alex28sh commented on Main.hs
> +applyAll (f:fs) x = f x : applyAll fs x
same

2024-09-26 23:31 UTC, alex28sh commented on Main.hs
> +interleave [] ys = []
you can implement this in one line using higher-order functions discussed in the lecture

2024-09-26 23:31 UTC, alex28sh requested changes
3/8

2024-09-30 13:07 UTC, kajigor requested changes

2024-09-30 13:07 UTC, kajigor commented on Main.hs
> +    | otherwise = foldl (*) 1 (zipWith (-) xs (tail xs))
This is a very contrived way to do something trivial. Just pattern match on the list instead of using guards.

2024-09-30 13:07 UTC, kajigor commented on Main.hs
> +applyAll fs x = map (\f -> f x) fs
You can use operator sections to avoid a lambda-function. Could you figure out how?

2024-10-04 12:13 UTC, kajigor commented
ok.

2024-10-04 12:13 UTC, closed without merging