Georgi Shopov HW02
kajigor/fp-2024-cub-fall pull request #43
Opened 2024-09-26 22:46 UTC by georgiiishopovv

2024-09-26 23:36 UTC, alex28sh commented on Main.hs
> +    in all (==True) z
you can implement `isSorted` in 1 line

2024-09-26 23:36 UTC, alex28sh commented on Main.hs
> +countElement _ [] = 0
don't need this case

2024-09-26 23:37 UTC, alex28sh commented on Main.hs
> +dotProduct [] [] = 0
don't need this case

2024-09-26 23:37 UTC, alex28sh commented on Main.hs
> +applyAll (x:xs) y = x y : applyAll (xs) y
use higher-order functions here

2024-09-26 23:37 UTC, alex28sh commented on Main.hs
> +interleave' (x:xs) (y:ys) = x : y : interleave' xs ys
you can implement it in 1 line using higher-order functions discussed in the lecture

2024-09-26 23:38 UTC, alex28sh requested changes
3/8

2024-10-04 12:16 UTC, kajigor commented on Main.hs
> +isSorted xs = all (==True) $ zipWith (<=) xs (drop 1 xs)
`all (==True)` could also be written as `all id` or, what is better, `and`.

2024-10-04 12:16 UTC, kajigor commented
ok

2024-10-04 12:16 UTC, closed without merging