Borovlev Petr HW03
kajigor/fp-2024-cub-fall pull request #45
Opened 2024-10-01 07:33 UTC by petyb

2024-10-01 10:19 UTC, kajigor commented on Main.hs
> +  a == b = show a == show b
This isn't a good way to implement equality.

2024-10-01 10:20 UTC, kajigor commented on Main.hs
> +  _ == _ = False
Whenever your implementation of a type class is trivial, it's better to derive it.

2024-10-01 10:22 UTC, kajigor commented on Main.hs
> +                  (_, Left b) -> Left b
There is a lot of code repetition which you can get rid of by introducing a helper function.

2024-10-01 10:23 UTC, kajigor commented on Main.hs
> +           | NegativeNumberSqrt
It could also be beneficial to report the sub-expression evaluation of which produced the error.

2024-10-01 13:22 UTC, kajigor commented
And make sure github action passes next time.

2024-10-04 12:20 UTC, kajigor commented
There are still issues in the code.

2024-10-04 14:37 UTC, petyb commented
> There are still issues in the code.
I think I fixed everything you mentioned above

2024-10-07 08:21 UTC, kajigor requested changes

2024-10-07 08:45 UTC, petyb commented on Main.hs
> +  a == b = eval a == eval b
it was not mentioned in the task how to compare expressions, kinda made sense to compare them by value

2024-10-07 09:10 UTC, petyb commented on Main.hs
> +  a == b = eval a == eval b
fixed

2024-10-07 09:10 UTC, petyb commented on Main.hs
> +import System.Win32 (xBUTTON1)
fixed

2024-10-07 10:10 UTC, kajigor commented on Main.hs
> +  a == b = eval a == eval b
> it was not mentioned in the task how to compare expressions, kinda made sense to compare them by value

It's indeed *a* way to compare expressions. The issue is that it's not scalable: you won't be able to implement such a notion of equality when we introduce variables. Even if you've managed to do it, it won't be that useful. Imagine we've implemented an optimization pass which gets rid of multiplication by 1: `1 * (x - y) -> x - y`. Now we want to write some tests that check whether the optimization is performed correctly. With your notion of equality, these two expressions are indistinguishable, so your test would test nothing. 

`Eq` should express syntactic equality in general, unless there's a specific reason to have a different notion of it. Unfortunately, I'm struggling to find examples of this in published libraries.

2024-10-07 10:11 UTC, kajigor commented on Main.hs
> +  (NegativeNumberSqrt _) == (NegativeNumberSqrt _) = True
This is not a great way to compare errors either: there is a difference between `ZeroDivision (Num 0)` and `ZeroDivision (Minus (Num 1) (Num 1))`.

2024-10-07 10:11 UTC, closed without merging