Hw01
kajigor/fp-2024-cub-fall pull request #8
Opened 2024-09-17 18:28 UTC by georgiiishopovv

Georgi Shopov

2024-09-19 16:15 UTC, kajigor requested changes

2024-09-19 16:15 UTC, kajigor commented on Main.hs
> +lovely a = (short a) || thirdElement a
Try to avoid unnecessary parentheses.

2024-09-19 16:15 UTC, kajigor commented on Main.hs
> +short (x:y:z:_) = False
It's better to use wildcards when you are not using the names introduced in a pattern match.

2024-09-26 22:54 UTC, alex28sh commented on Main.hs
> +      thirdElement (_:_:x:_) = if x == 14 then True else False
too much overhead

thirdElement (_:_:14:_) = True - is much easier

2024-09-26 22:58 UTC, alex28sh commented on Main.hs
> +short (_:_:_:_) = False
last 2 cases can be united

2024-09-26 23:00 UTC, alex28sh reviewed
ok

2024-09-26 23:00 UTC, closed without merging