Georgi Shopov HW05
kajigor/fp-2024-cub-fall pull request #86
Opened 2024-10-24 13:48 UTC by georgiiishopovv

2024-11-04 11:08 UTC, kajigor requested changes

2024-11-04 11:08 UTC, kajigor commented on monads/src/HW/Eval.hs
> +   (MachineState s1 e1) == (MachineState s2 e2) = s1 == s2 && e1 == e2
Derive.

2024-11-04 11:08 UTC, kajigor commented on monads/src/HW/Eval.hs
> +   return (Right ())
You don't need this return.

2024-11-04 11:08 UTC, kajigor commented on monads/src/HW/Eval.hs
> +   state <- get
Use `gets`

2024-11-12 10:36 UTC, kajigor commented
Resolve the conflict ^

2024-11-14 16:28 UTC, georgiiishopovv commented
> Resolve the conflict

Fixed <2 days ago>

2024-12-01 12:11 UTC, kajigor commented
Ok

2024-12-01 12:11 UTC, closed without merging